### ISSUE TITLE
Is Micro Manager Python Support Python3?

### ISSUE THREAD

**Issue by TaylorHere** [radioxoma/micromanager-samples#1]
Python 2.7 will reach the end of its life on January 1st, 2020.
Do we hope Micro Manager support Python3, Is that in the plan?

**Comment by radioxoma** [comment]
I'm not affiliated with Micro-manager. This repo is just a remembrance from my past.

**Yes.** Source code already supports python3. Which python version is being used defined during compilation, like in that [Archlinux PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=micromanager-git&id=4b0150680d48734a8b5d7fc4cacb361caf51c64c#n53). Please [contact](https://micro-manager.org/wiki/Contact) Micromanager dev team for python3 builds.

**Comment by TaylorHere** [comment]
ありがとう
